### ISSUE TITLE
条形图的名称

### ISSUE THREAD

**Issue by LalZzy** [MikeLYX/bar-graph#4]
直立条形图与横躺条形图，是不是表述为：柱状图与条形图 更恰当。

**Comment by MikeLYX** [comment]
直立条形图和横躺条形图代表的是两种条形图，但是条形图和柱状图是不一样的：柱状图表示的是横坐标是量化数据，不能重新排序的图形；而条形图的横坐标更多的是表示类别上的区分，也就是说可以进行重新排序的。柱状图和条形图的区别和坐标是否横向排列没有关系。可以看一下<http://www.forbes.com/sites/naomirobbins/2012/01/04/a-histogram-is-not-a-bar-chart/>这篇文章

**Comment by LalZzy** [comment]
感谢回复，对于你提到的这篇文章，histogram在统计学中约定俗成的翻译应当是“直方图”吧，并非我所述的柱状图。
我又去查阅了一些资料，似乎‘bar plot’翻译为条形图与柱状图均可，与是否横向排列没有关系，这点你说的对。综上，你的表述没有问题。
以及我也是从统计之都原贴里follow来的，阅读了你的这篇文章，私以为开头是那副不怎么美观的条形图，那么紧接着对其批判一番后再引出绘图原则与艺术，段落文字会不会更自然些？如果能见到统计之都上这篇文章发表，更是再好不过了。

**Comment by MikeLYX** [comment]
嗯嗯好的，我会考虑你的建议，当然，这篇文章自然会投到统计之都上去。
