### ISSUE TITLE
文章修改

### ISSUE THREAD

**Issue by MikeLYX** [MikeLYX/bar-graph#5]
@Cloud2016 我刚刚补上了图18的代码，这些图有些问题要和师兄探讨一下：
1.图11,12,14,15这几张图的代码不是R的，是否应该放上去，我觉得还是放上去的好，不过标明是什么代码（但实际上我的确不太知道这个是什么软件的代码...）；
2.后面师兄又加的那个复合堆积条形图的反例，我个人感觉没啥问题，颜色不多， 也较容易区分，表现的也很明显...师兄能否说一下这个反例反在了哪里？
3.后面师兄所加的马赛克图，这个我只是听说过，但很少接触，能否说一下它的大致含义？

**Comment by XiangyunHuang** [comment]
@MikeLYX 
1. 这几个图都是[gnuplot](http://gnuplot.sourceforge.net/)画的，不是我画的，来自gnuplot官网demos，因此我在参考文献出给了
<http://gnuplot.sourceforge.net/demo/histograms.html> 和 <http://gnuplot.sourceforge.net/demo/histograms2.html> 两个链接，链接所在网页也包含绘图代码

2. 这里堆积得多，分类也挺多的，我觉得这个时候马赛克图比之更好些

![stackplot](https://user-images.githubusercontent.com/12031874/29699745-a81b58a8-8991-11e7-9996-2f0a4ada46f7.png)
![stackmosaicplot](https://user-images.githubusercontent.com/12031874/29699751-b0485c24-8991-11e7-8f7f-e059959676c9.png)

3. 去掉数值上的准确量化代之以直观的大小比较，而且视觉上对方块比较好识别
详细可见 <http://epub.wu.ac.at/480/1/document.pdf>

**Comment by MikeLYX** [comment]
@Cloud2016 好的，那我再把文稿修改一下，加上马赛克图，其他部分师兄觉得哪里还有问题，我直接一并修改了

**Comment by XiangyunHuang** [comment]
@MikeLYX 复合堆积条形图和马赛克图（在比较大小时也可看作矩阵树图treemap）结合益辉给的关于图感知和可视化设计那篇文章结论（文章中图4），马赛克图有优势。这个结论是基于比例比较，重在对比比较方面，如果说硬要强调数值大小，那复合堆积条形图稍好，说来说去，各有千秋。

**Comment by XiangyunHuang** [comment]
@MikeLYX  我加下你的微信怎么样？或者你加我的也行，为便于及时讨论。我的微信号是Sophorae
